// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhLbusXPo_lmuxZkXBUTsO_JiBv0uNWM',
    appId: '1:550081743591:web:e13c93909b6af9e80af042',
    messagingSenderId: '550081743591',
    projectId: 'ammarii',
    authDomain: 'ammarii.firebaseapp.com',
    storageBucket: 'ammarii.firebasestorage.app',
    measurementId: 'G-RKCHQ8Z5LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOlw9ikEst6o3P5hJumhvP2pgkIF-0sA',
    appId: '1:550081743591:android:f2caff9606846e940af042',
    messagingSenderId: '550081743591',
    projectId: 'ammarii',
    storageBucket: 'ammarii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa69cbUOMI72O0Stk2rjhZeKxHTO4_vZE',
    appId: '1:550081743591:ios:ede31a3bafb3b3ea0af042',
    messagingSenderId: '550081743591',
    projectId: 'ammarii',
    storageBucket: 'ammarii.firebasestorage.app',
    iosBundleId: 'com.achraaafapp.achraaafapp',
  );
}
